version: "3"
services:
  user-verification-service:
    build: ./user-verification-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://consigned_client:3306/consigned_client
    depends_on:
      - user-verification-db
  #  consigned-simulator-service:
  #    build: ./consigned-simulator-service
  #    ports:
  #      - "8082:8082"
  #    environment:
  #      - SPRING_DATASOURCE_URL=jdbc:mysql://consigned_simulation:3306/consigned_simulation
  #    depends_on:
  #      - mysql
  #  consigned-contract-service:
  #    build: ./consigned-contract-service
  #    ports:
  #      - "8083:8083"
  #    environment:
  #      - SPRING_DATASOURCE_URL=jdbc:mysql://consigned_contract:3306/consigned_contract
  #    depends_on:
  #      - mysql
  user-verification-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: consigned_client
    volumes:
      - user-verification-data:/var/lib/mysql

  zookeeper:
    container_name: zookeeper
    image: "bitnami/zookeeper:latest"
    networks:
      - kafka-net
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: kafka
    image: "bitnami/kafka:latest"
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper

volumes:
  user-verification-data:

networks:
  kafka-net:
    driver: bridge