version: "3"
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    networks:
      - kafka-net
    environment:
      - spring.main.web-application-type=reactive
    depends_on:
      - user-verification-service
      - consigned-simulator-service
      - consigned-contract-service

  user-verification-service:
    build: ./user-verification-service
    image: user-verification-service:latest
    ports:
      - "8081:8081"
    networks:
      - kafka-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://user-verification-db:3306/consigned_client
    depends_on:
      - user-verification-db
  user-verification-db:
    image: mysql:8.0
    networks:
      - kafka-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: consigned_client
    volumes:
      - user-verification-data:/var/lib/mysql

  consigned-simulator-service:
    build: ./consigned-simulator-service
    image: consigned-simulator-service:latest
    ports:
      - "8082:8082"
    networks:
      - kafka-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://consigned-simulator-db:3306/consigned_simulation
      - CONSIGNED_VERIFICATION_URL=http://user-verification-service:8081/api/v1/client/
    depends_on:
      - consigned-simulator-db
  consigned-simulator-db:
    image: mysql:8.0
    networks:
      - kafka-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: consigned_simulation
    volumes:
      - consigned-simulator-data:/var/lib/mysql
      - ./database/simulation/script_creation_database_simulation.sql:/docker-entrypoint-initdb.d/script_creation_database_simulation.sql
      - ./database/simulation/script_initial_simulation.sql:/docker-entrypoint-initdb.d/script_initial_simulation.sql
      - ./database/procedure/SIMU_PROC_REGISTRATION_SIMULATION.sql:/docker-entrypoint-initdb.d/SIMU_PROC_REGISTRATION_SIMULATION.sql

  consigned-contract-service:
    build: ./consigned-contract-service
    image: consigned-contract-service:latest
    ports:
      - "8083:8083"
    networks:
      - kafka-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://consigned-contract-db:3306/consigned_contract
    depends_on:
      - consigned-contract-db
  consigned-contract-db:
    image: mysql:8.0
    networks:
      - kafka-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: consigned_contract
    volumes:
      - consigned-contract-data:/var/lib/mysql

  zookeeper:
    container_name: zookeeper
    image: "bitnami/zookeeper:latest"
    networks:
      - kafka-net
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: kafka
    image: "bitnami/kafka:latest"
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper

volumes:
  user-verification-data:
  consigned-simulator-data:
  consigned-contract-data:

networks:
  kafka-net:
    driver: bridge