-- Schema consigned_client
CREATE SCHEMA IF NOT EXISTS consigned_client;
USE consigned_client;

-- Table TCLI_DOCUMENT_TYPE
CREATE TABLE IF NOT EXISTS TCLI_DOCUMENT_TYPE (
  ID_DOC INT NOT NULL,
  DOC_TYPE VARCHAR(30) NOT NULL,
  PRIMARY KEY (ID_DOC),
  UNIQUE (DOC_TYPE)
) ENGINE = InnoDB;

-- Table TCLI_SEGMENT_TYPE
CREATE TABLE IF NOT EXISTS TCLI_SEGMENT_TYPE (
  ID_SEGM INT NOT NULL,
  SEGM_TYPE VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID_SEGM),
  UNIQUE (SEGM_TYPE)
) ENGINE = InnoDB;

-- Table TCLI_AGREEMENT_TYPE
CREATE TABLE IF NOT EXISTS TCLI_AGREEMENT_TYPE (
  ID_AGRM INT NOT NULL,
  AGMR_TYPE VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID_AGRM),
  UNIQUE (AGMR_TYPE)
) ENGINE = InnoDB;

-- Table TCLI_CLIENT
CREATE TABLE IF NOT EXISTS TCLI_CLIENT (
  DOC_CLIENT VARCHAR(64) PRIMARY KEY,
  ID_DOCUMENT INT NOT NULL,
  NAME_CLIENT VARCHAR(45) NOT NULL,
  ACCOUNT_HOLDER TINYINT(1) NOT NULL,
  ID_SEGMENT INT,
  ID_AGREEMENT INT NOT NULL,
  INCLUSION_DATE DATETIME NOT NULL,
  INDEX fk_TCLI_CLIENT_TCLI_AGREEMENT_TYPE_idx (ID_AGREEMENT),
  INDEX fk_TCLI_CLIENT_TCLI_DOCUMENT_TYPE_idx (ID_DOCUMENT),
  INDEX fk_TCLI_CLIENT_TCLI_SEGMENT_TYPE_idx (ID_SEGMENT),
  CONSTRAINT fk_TCLI_CLIENT_TCLI_AGREEMENT_TYPE
    FOREIGN KEY (ID_AGREEMENT)
    REFERENCES TCLI_AGREEMENT_TYPE (ID_AGRM)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_TCLI_CLIENT_TCLI_DOCUMENT_TYPE
    FOREIGN KEY (ID_DOCUMENT)
    REFERENCES TCLI_DOCUMENT_TYPE (ID_DOC)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_TCLI_CLIENT_TCLI_SEGMENT_TYPE
    FOREIGN KEY (ID_SEGMENT)
    REFERENCES TCLI_SEGMENT_TYPE (ID_SEGM)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;
